### ISSUE TITLE
No "stahl.csv" data can be found

### ISSUE THREAD

**Issue by Running-z** [Gananath/DrugAI#2]
The data file "stahl.csv" in DrugAI-Gen.py has not been found. Can you explain it to me?
![default](https://user-images.githubusercontent.com/38971699/41982055-078f96f2-7a5d-11e8-81a5-9423b7fd05ae.png)

**Comment by Running-z** [comment]
@Gananath 
Could you give me a note, please?

**Comment by Gananath** [comment]
Sorry, I didn't renamed the [stahl-dataset.csv ](https://github.com/Gananath/DrugAI/blob/master/stahl-dataset.csv) file you have to rename it yourself as `stahl.csv`.
